/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dx.timesheet;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;

/**
 *
 * @author Me
 */
public class ExtendDeadlineDialog extends javax.swing.JDialog {

    //   JXDatePicker d_picker;
    HardwareDetails hd = new HardwareDetails();
    String comments = "";
    String timeInHour="",timeInMin="";
    SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yyyy");
    TaskPanel ts = new TaskPanel();
    static String flag = "";
    java.awt.Frame frame;

    public String getTimeInHour() {
        return timeInHour;
    }

    public String getTimeInMin() {
        return timeInMin;
    }
    /**
     * Creates new form ExtendDeadlineDialog
     */
    public ExtendDeadlineDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //       d_picker=new JXDatePicker();
        //      d_picker.setBounds(105, 65, 125, 25);
        //      d_picker.setDate(Calendar.getInstance().getTime());
        d_picker.setFormats(new SimpleDateFormat("dd-MMM-yyyy"));
        d_picker.getMonthView().setLowerBound(new Date());
        d_picker.setLocation(0, 0);
        //    d_picker.getMonthView().setFlaggedDates(new Date());
        //  d_picker.getMonthView().set
        //    jPanel7.add(d_picker);
        //  frame.getContentPane().add(panel);
    }

    public String getDate() {
        System.out.println(comments);
        return comments;
    }

    public String getFlag() {
        return flag;
    }

    public void setDate(String s) {
        lblDeadline.setText(s);
    }

    public void setCurrentDate() {
        d_picker.setDate(Calendar.getInstance().getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblInput3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnExit3 = new javax.swing.JButton();
        btnOk3 = new javax.swing.JButton();
        lblDeadline = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        d_picker = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        spinnerHour = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinnerMin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(230, 135));

        lblInput3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInput3.setText("Old Deadline:");

        jPanel8.setBackground(new java.awt.Color(15, 161, 208));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        btnExit3.setText("Cancel");
        btnExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit3ActionPerformed(evt);
            }
        });

        btnOk3.setText("Apply");
        btnOk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk3ActionPerformed(evt);
            }
        });

        lblDeadline.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblDeadline.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Select New Deadline:");

        d_picker.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        d_picker.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        d_picker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_pickerActionPerformed(evt);
            }
        });
        d_picker.getEditor().setEditable(false);

        jLabel3.setText("HH:");

        spinnerHour.setModel(new javax.swing.SpinnerNumberModel(0,0, 23, 1));
        spinnerHour.setEditor(new JSpinner.DefaultEditor(spinnerHour));

        jLabel4.setText("MM:");

        spinnerMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spinnerMin.setEditor(new JSpinner.DefaultEditor(spinnerMin));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblInput3)
                        .addGap(3, 3, 3)
                        .addComponent(lblDeadline))
                    .addComponent(jLabel2)
                    .addComponent(d_picker, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnOk3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(spinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput3)
                    .addComponent(lblDeadline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(d_picker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk3)
                    .addComponent(btnExit3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit3ActionPerformed
        flag = "";
        comments = "";
        dispose();
    }//GEN-LAST:event_btnExit3ActionPerformed

    private void btnOk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk3ActionPerformed
        long deaddate = 0, newdate = 0;
        Calendar now = Calendar.getInstance();
        Date time=now.getTime();
        timeInHour=spinnerHour.getValue().toString();
        timeInMin=spinnerMin.getValue().toString();
        System.out.println(timeInHour+"-"+timeInMin);
        try {
            deaddate = hd.convertDateToMillis(lblDeadline.getText().toString());
            newdate = hd.convertDateToMillis(sd.format(d_picker.getDate()));

            System.out.println("deaddate:::" + deaddate);
            System.out.println("newdate:::" + newdate);
            //if (newdate > deaddate) {
            if(timeInHour.equals("0") && timeInMin.equals("0") ){

                flag = "wrong";
                System.out.println(".........New date is wrong...........");
                setVisible(false);
            } else {
                    flag = "correct";
                    System.out.println("FLAG--->>>"+flag);
                    comments = sd.format(d_picker.getDate());
                    System.out.println("comment-->>"+comments);
                    setVisible(false);
                    
            }
        } catch (Exception ex) {
            showInfoDialog("Incorrect date or time");
            Logger.getLogger(ExtendDeadlineDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnOk3ActionPerformed

    private void d_pickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_pickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_pickerActionPerformed
    public void showInfoDialog(String Info) {
        InfoDialog inf = new InfoDialog(frame, true);
        inf.setLocationRelativeTo(this);
        inf.setInfo(Info);
        inf.setVisible(true);

    }
public void setDialog(java.awt.Frame parent ){
       frame=parent;
   }
   public java.awt.Frame getDialog(){
        return frame;
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
                            
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtendDeadlineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtendDeadlineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtendDeadlineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtendDeadlineDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExtendDeadlineDialog dialog = new ExtendDeadlineDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit3;
    public static javax.swing.JButton btnOk3;
    public org.jdesktop.swingx.JXDatePicker d_picker;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JLabel lblDeadline;
    public javax.swing.JLabel lblInput3;
    public javax.swing.JSpinner spinnerHour;
    public javax.swing.JSpinner spinnerMin;
    // End of variables declaration//GEN-END:variables
}
